kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8000
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8001
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8002
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8003
    listenAddress: "0.0.0.0"
    protocol: udp