apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vovcha-ingress
  namespace: vovcha
spec:
  rules:
  - host: cluster-vovcha
    http:
      paths:
      - path: /all-users
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 80
      - path: /create-user
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 80
      - path: /circle-area
        pathType: Prefix
        backend:
          service:
            name: mathematic-service
            port:
              number: 80