apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: vovcha
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-server
        image: fastapi-server:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-volume
          mountPath: /tmp/fastapi-cache
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 100Mi