apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: vovcha
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-server
        image: fastapi-server:v1
        env:
          - name: UVICORN_PORT
            valueFrom:
              configMapKeyRef:
                name: webapp-conf
                key: uvicorn_port_listen
          - name: DEFAULT_RESPONSE_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: webapp-conf
                key: default_response_message
          - name: REDIS_DEFAULT_USER_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: webapp-conf
                key: redis_default_user_password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-volume
          mountPath: /tmp/fastapi-cache
        # - name: static-data-volume
        #   mountPath: /app/static
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 100Mi
      # - name: static-data-volume
      #   persistentVolumeClaim:
      #     claimName: static-data-claim