apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data-claim
  namespace: vovcha
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi