apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-conf
  namespace: vovcha
data:
  uvicorn_port_listen: "80"
  default_response_message: "Godmode."
  redis_default_user_password: "zXHCvD9BtF"   # kubectl get secret --namespace redis redis -o jsonpath="{.data.redis-password}" | base64 -d