apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: vovcha
spec:
  type: ExternalName
  externalName: redis-master.redis.svc.cluster.local
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379